#spring:
#  datasource:
#    url : "jdbc:postgresql://34.93.210.170/virtual-reality"
#    username: "vrpd"
#    password: "postgress"
#    driverClassName: "org.postgresql.Driver"
#  jpa:
#    hibernate:
#      ddl-auto: "update"
#
#  cloud:
#    gcp:
#      logging:
#        enabled: true