spring:
  datasource:
    url : "jdbc:postgresql://localhost:5432/hashhomes"
    username: "postgres"
    password: "123"
    driverClassName: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"